# https://yarnpkg.com/configuration/yarnrc

nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.0.2.cjs

# yarn cache setting
enableGlobalCache: false
cacheFolder: './.yarn/cache'

# .yarn/unplugged 디렉토리 이슈로 off (https://yarnpkg.com/getting-started/qa)
enableScripts: false

# 배포환경의 os 설정
supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
  os:
    - darwin
    - linux
    - win32
